# Generated by Django 4.2.8 on 2024-01-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiobooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_votes', models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество голосов')),
                ('sum_points_plot', models.FloatField(default=8.17601832691292, verbose_name='Сюжет, все балы')),
                ('plot', models.FloatField(default=0.0, verbose_name='Сюжет, средний бал')),
                ('sum_points_writing_talent', models.FloatField(default=8.34540410983878, verbose_name='Писательский талант, все балы')),
                ('writing_talent', models.FloatField(default=0.0, verbose_name='Писательский талант, средний бал')),
                ('sum_points_voice_quality', models.FloatField(default=8.876808288808917, verbose_name='Качество озвучивания, все балы')),
                ('voice_quality', models.FloatField(default=0.0, verbose_name='Качество озвучивания, средний бал')),
                ('total_ratings', models.IntegerField(default=0, verbose_name='Общий рейтинг')),
                ('like', models.IntegerField(default=5, verbose_name='Нравится(+)')),
                ('dislike', models.IntegerField(default=1, verbose_name='Не нравится(-)')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='average_rating', to='audiobooks.modelbooks', verbose_name='Книга')),
            ],
        ),
    ]
