# Generated by Django 4.2.8 on 2024-01-14 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='averagerating',
            old_name='writing_talent',
            new_name='talent',
        ),
        migrations.RenameField(
            model_name='averagerating',
            old_name='voice_quality',
            new_name='voice',
        ),
        migrations.RemoveField(
            model_name='averagerating',
            name='sum_points_plot',
        ),
        migrations.RemoveField(
            model_name='averagerating',
            name='sum_points_voice_quality',
        ),
        migrations.RemoveField(
            model_name='averagerating',
            name='sum_points_writing_talent',
        ),
        migrations.AddField(
            model_name='averagerating',
            name='downloads',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество загрузок'),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='sum_plot',
            field=models.IntegerField(default=0, verbose_name='Сюжет, все балы'),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='sum_talent',
            field=models.IntegerField(default=0, verbose_name='Писательский талант, все балы'),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='sum_voice',
            field=models.IntegerField(default=0, verbose_name='Качество озвучивания, все балы'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Не нравится(-)'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Нравится(+)'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='number_votes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество голосов'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='total_ratings',
            field=models.FloatField(default=0, verbose_name='Общий рейтинг'),
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.IntegerField(default=0, verbose_name='Сюжет')),
                ('talent', models.IntegerField(default=0, verbose_name='Писательский талант')),
                ('voice', models.IntegerField(default=0, verbose_name='Качество озвучивания')),
                ('like_dislike', models.IntegerField(blank=True, null=True, verbose_name='Лайк/Дизлайк')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='audiobooks.modelbooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
